[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
handlebars = "6.2.0"
serde_json = "1.0.133"
num-bigint = "0.4.6"
num-traits = "0.2.19"
